### ISSUE TITLE
Show where the passwords in config PHP files were found.

### ISSUE THREAD

**Issue by CobraColin** [peass-ng/PEASS-ng#393]
This is what is right now.
╔══════════╣ Searching passwords in config PHP files
$password = "complexpassword";
$password = "complexpassword";

What is suggest is something like this:
╔══════════╣ Searching passwords in config PHP files

File path:  
       $password = "complexpassword";
Different file path:
       $password = "complexpassword";

Sometimes you also want to know where it was found because there might be other useful information in the config file such a username.

**Comment by takitakitanana** [comment]
Guess this can be closed.
Wanted to tackle this but changes already made with commit 05f6cb7.
