### ISSUE TITLE
Unable to skip deep file scans in WinPEASx64

### ISSUE THREAD

**Issue by jeffkkimura** [peass-ng/PEASS-ng#399]
#### Issue description

Unable to skip DB scan in WinPEASx64.

#### Steps to reproduce the issue

1.  Run WinPEASx64 w -skip_files "file_check1,file_check2,db_check1,db_check2" 
2.  Attempted to skip using winpeasx64.exe -skip_files all

#### Which parameters did you use for executing the script and how did you execute it?
-skip_files all
-skip_files file_check1,file_check2,db_check1,db_check2
--fast

#### If winpeas, did you use a clean or obfuscated winpeas, and for which architecture?
Clean, x64

#### Is there any AV / Threat protection in the system?
No

#### Please, indicate the OS, the OS version, and the kernel version (build number in case of Windows)
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000

#### Please, indicate the check that is failing and add a screenshot showing the problem
![image](https://github.com/carlospolop/PEASS-ng/assets/28190943/474a4f80-fd5d-4e89-b59c-e40ede9b1234)

#### How did you expect it to work?
Find an option to run a quick scan avoiding all deep file scans.

**Comment by carlospolop** [comment]
Hi @jeffkkimura, from now on fileanalysis won't be executed by default and you will need to specifically indicate so when you want to execute it.
