### ISSUE TITLE
Support for Windows LAPS

### ISSUE THREAD

**Issue by darses** [peass-ng/PEASS-ng#423]
This is a feature request to detect the (newer) Windows LAPS in addition to the current (legacy) Microsoft LAPS. I have only checked winPEAS.bat, but this feature request may also be relevant to winPEAS.ps1 and winPEAS.exe.

The [LAPSInstallCheck in winPEAS.bat](https://github.com/peass-ng/PEASS-ng/blob/a2fb2cd2be5cac4af2264953ecf45380aacd4942/winPEAS/winPEASbat/winPEAS.bat#L149) checks the (legacy) Microsoft LAPS status looking at the registry value(s) at `HKEY_LOCAL_MACHINE\Software\Policies\Microsoft Services\AdmPwd`. The newer [Microsoft LAPS](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview) variant uses a different registry value at `HKLM\Software\Microsoft\Policies\LAPS`, `HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\LAPS` and `HKLM\Software\Microsoft\Windows\CurrentVersion\LAPS\Config`. See also the documentation at [Supported policy roots](https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-management-policy-settings#supported-policy-roots).

**Comment by carlospolop** [comment]
Could you send a PR?
