### ISSUE TITLE
LinPeass highlights in yellow only the two final letters at the end of a sudo restriction

### ISSUE THREAD

**Issue by simonetablo** [peass-ng/PEASS-ng#425]
When linpeass performs checks related to sudo allowed commands (sudo -l), it returns the following results:

Matching Defaults entries for user1 on host:
    env_reset, mail_badpass, secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin

User user1 may run the following commands on host:
    (ALL) /bin/ls /tmp/backup/backup_access
    (root) /usr/bin/cat backup_access

The strange thing is that it highlights in yellow (marking as 95% a PE vector) the last two letters (ss) of the directories where the user can execute the listed commands.
Are those real PE vectors or is a bug?

![Screenshot_2024-05-28_14-25-50](https://github.com/peass-ng/PEASS-ng/assets/102805890/6d757937-5082-4f3c-a076-2e6c89dbdb85)

**Comment by carlospolop** [comment]
Colors highlights info using regexes. In that case it's just a false positive as the color is not highlighting the whole name of the binary.
In any case this commit: https://github.com/peass-ng/PEASS-ng/commit/7a9ea40cbbe5c4e345dd460fefcfc15c14ebf05d should help to reduce this kind of false positives
